version: '3'

services:
  db:
    container_name: 'dockerize_rails_k8s_db'
    image: 'postgres:9.6-alpine'
    env_file: '.db.env'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  app:
    container_name: 'dockerize_rails_k8s_app'
    depends_on:
      - 'db'
    build:
      context: '.'
      dockerfile: 'Dockerfile.app.dev'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file: '.app.env'
  nginx:
    container_name: 'dockerize_rails_k8s_nginx'
    depends_on:
      - 'app'
    build:
      context: '.'
      dockerfile: 'Dockerfile.nginx.dev'
    ports:
      - '80:80'
volumes:
  postgres: