version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
              pip install \
              docker-compose
      - run:
          name: Start docker compose
          command: |
            docker-compose -f docker-compose.test.yml up --build -d
      - run: docker-compose run --rm app rails db:environment:set RAILS_ENV=test
      - run: docker-compose run --rm app rails db:schema:load RAILS_ENV=test
      - run:
          name: Run tests
          command: |
            docker-compose run --rm app rspec