
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Start docker-compose
          command: docker-compose up --build -d
      # - run:
      #     name: sleep for waiting launch db
      #     command: sleep 1
      - run:
          name: "before_test: setup db"
          command: docker-compose run --rm app rails db:create db:migrate
      - run:
          name: Run test
          command: docker-compose run --rm app rspec
      - run:
          name: Stop docker-compose
          command: docker-compose down